Recursive filter for memberOf attr
MultiDirectoryLab/MultiDirectory pull request #303
Opened 2024-08-28 13:30 UTC by rimu-stack

2024-08-28 13:41 UTC, GamePad64 requested changes

2024-08-28 13:41 UTC, GamePad64 commented on app/ldap_protocol/filter_interpreter.py
> +        if ':1.2.840.113556.1.4.1941:' in attribute:
Нужно вынести oid в константу

2024-08-28 13:41 UTC, GamePad64 commented on app/ldap_protocol/filter_interpreter.py
> +    if attribute.startswith('memberof'):  # noqa: R505
Достаточно сравнения через ==, ниже -- тоже

2024-08-28 13:41 UTC, GamePad64 commented on app/ldap_protocol/filter_interpreter.py
> +    elif item.attr.startswith('member'):
Раньше было более читаемо, типа, есть два варианта: member и memberof

2024-08-28 14:13 UTC, GamePad64 approved these changes

2024-08-29 03:50 UTC, Mastermind-U commented on app/ldap_protocol/filter_interpreter.py
> +    path_filter = get_path_filter(group_path)
Сделай функцию get_filter_from_path, она давно напрашивалась

2024-08-29 03:50 UTC, Mastermind-U commented on app/ldap_protocol/filter_interpreter.py
> +    elif attr.startswith('member'):
Лучше оставить старую проверку, `attr in {'memberof', 'member'}`, клиенты могут любой кастомный атрибут подсунуть

2024-08-29 03:50 UTC, Mastermind-U commented on app/ldap_protocol/filter_interpreter.py
> +        select(text("directory_id"))
`select(Directory.directory_id)`

2024-08-29 03:50 UTC, Mastermind-U commented on app/ldap_protocol/filter_interpreter.py
> +            directory_hierarchy.c.group_id == DirectoryMembership.group_id)
Почему тут не релейшншипы?

2024-08-29 03:50 UTC, Mastermind-U commented on app/ldap_protocol/filter_interpreter.py
> +    """Retrieve query conditions with the memberOF attribute(recursive)."""
Опиши в докстринге подробную работу функции, с примерами и схемой, так ничего не понятно

2024-08-29 11:50 UTC, merged